/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import java.awt.Image;
import java.net.URL;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author xp
 */
public class VentanaAhorcado2 extends javax.swing.JFrame {

String palabraOculta = "CETYS";
int numeroDeFallos = 0;
    /**
     * Creates new form VentanaAhorcado2
     */
    public VentanaAhorcado2() {
        initComponents();
        //Inicializo la imagen del label del ahorcado
        dibujaImagen(NORMAL);
         dibujaImagen(0);
 	palabraOculta = escogePalabra();
    }
    private void checkbarras() {
        String barras = "";
        for (int i = 0; i < palabraOculta.length(); i++) {
            barras += "_ ";   
        }
 	jLabel1.setText(barras);	 
    }
        private String escogePalabra(){
	String palabra = "CETYS";
	String[] listaPalabras = {"hola","adios","esternocleidomastoideo","piña","CETYS"};
	Random random = new Random();
	palabra = listaPalabras[random.nextInt(listaPalabras.length)];
	palabra = palabra.toUpperCase();
	return palabra;
    }
    private void chequeaLetra(String letra){
        URL nombreImagen;
        letra = letra.toUpperCase();
        String palabraConGuiones = jLabel1.getText();
        
        boolean acierto = false;
        for(int i=0; i<palabraOculta.length(); i++){
            if(palabraOculta.charAt(i)== letra.charAt(0)){
                //TODO quita el guion bajo de la letra correspondiente
                palabraConGuiones = palabraConGuiones.substring(0,2*i) + letra + palabraConGuiones.substring(2*i +1);
                acierto = true;
            }
        }
        if (!palabraConGuiones.contains("_")){
              nombreImagen = getClass().getResource("/imagenes/acertasteTodo.png");
              int ancho =jLabel2.getWidth();
              int alto =jLabel2.getHeight();
              ImageIcon miImagen = new ImageIcon( new ImageIcon(nombreImagen).getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));
              jLabel2.setIcon(miImagen);
              
        }
        //actualizo el valor que se muestra en la pantalla con letras
        //adivinadas
        jLabel1.setText(palabraConGuiones);
        if(!acierto){
            numeroDeFallos++;
            dibujaImagen(numeroDeFallos);
        }
    }
    
    private void chequeaBoton(JButton _boton){
        _boton.setEnabled(false);
        chequeaLetra(_boton.getText());
    }
    private void dibujaImagen(int numeroImagen){
        URL nombreImagen;
        switch (numeroImagen){
            case 0 : nombreImagen = getClass().getResource("/imagenes/ahorcado_0.png"); break;
            case 1 : nombreImagen = getClass().getResource("/imagenes/ahorcado_1.png"); break;
            case 2 : nombreImagen = getClass().getResource("/imagenes/ahorcado_2.png"); break;
            case 3 : nombreImagen = getClass().getResource("/imagenes/ahorcado_3.png"); break;
            case 4 : nombreImagen = getClass().getResource("/imagenes/ahorcado_4.png"); break;
            case 5 : nombreImagen = getClass().getResource("/imagenes/ahorcado_5.png"); break;
            case 6 : nombreImagen = getClass().getResource("/imagenes/ahorcado_fin.png"); break;
            default : nombreImagen = getClass().getResource("/imagenes/ahorcado_fin.png"); break;
        }
       
        
        int ancho = jLabel2.getWidth();
        int alto = jLabel2.getHeight();
        ImageIcon miImagen = new ImageIcon( new ImageIcon(nombreImagen).getImage().getScaledInstance(ancho, alto,Image.SCALE_DEFAULT));
        
        jLabel2.setIcon(miImagen);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonA = new javax.swing.JButton();
        jButtonB = new javax.swing.JButton();
        jButtonC = new javax.swing.JButton();
        jButtonD = new javax.swing.JButton();
        jButtonE = new javax.swing.JButton();
        jButtonF = new javax.swing.JButton();
        jButtonG = new javax.swing.JButton();
        jButtonL = new javax.swing.JButton();
        jButtonM = new javax.swing.JButton();
        jButtonN = new javax.swing.JButton();
        jButtonH = new javax.swing.JButton();
        jButtonI = new javax.swing.JButton();
        jButtonJ = new javax.swing.JButton();
        jButtonK = new javax.swing.JButton();
        jButtonR = new javax.swing.JButton();
        jButtonS = new javax.swing.JButton();
        jButtonT = new javax.swing.JButton();
        jButtonÑ = new javax.swing.JButton();
        jButtonO = new javax.swing.JButton();
        jButtonP = new javax.swing.JButton();
        jButtonQ = new javax.swing.JButton();
        jButtonX = new javax.swing.JButton();
        jButtonY = new javax.swing.JButton();
        jButtonZ = new javax.swing.JButton();
        jButtonU = new javax.swing.JButton();
        jButtonV = new javax.swing.JButton();
        jButtonW = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("_ _ _ _ _");

        jButtonA.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonA.setText("A");
        jButtonA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonAMousePressed(evt);
            }
        });

        jButtonB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonB.setText("B");
        jButtonB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonBMousePressed(evt);
            }
        });

        jButtonC.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonC.setText("C");
        jButtonC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonCMousePressed(evt);
            }
        });

        jButtonD.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonD.setText("D");
        jButtonD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonDMousePressed(evt);
            }
        });

        jButtonE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonE.setText("E");
        jButtonE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonEMousePressed(evt);
            }
        });

        jButtonF.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonF.setText("F");
        jButtonF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonFMousePressed(evt);
            }
        });

        jButtonG.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonG.setText("G");
        jButtonG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonGMousePressed(evt);
            }
        });

        jButtonL.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonL.setText("L");
        jButtonL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonLMousePressed(evt);
            }
        });

        jButtonM.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonM.setText("M");
        jButtonM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonMMousePressed(evt);
            }
        });

        jButtonN.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonN.setText("N");
        jButtonN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonNMousePressed(evt);
            }
        });

        jButtonH.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonH.setText("H");
        jButtonH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonHMousePressed(evt);
            }
        });

        jButtonI.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonI.setText("I");
        jButtonI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonIMousePressed(evt);
            }
        });

        jButtonJ.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonJ.setText("J");
        jButtonJ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonJMousePressed(evt);
            }
        });

        jButtonK.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonK.setText("K");
        jButtonK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonKMousePressed(evt);
            }
        });

        jButtonR.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonR.setText("R");
        jButtonR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonRMousePressed(evt);
            }
        });

        jButtonS.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonS.setText("S");
        jButtonS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonSMousePressed(evt);
            }
        });

        jButtonT.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonT.setText("T");
        jButtonT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonTMousePressed(evt);
            }
        });

        jButtonÑ.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonÑ.setText("Ñ");
        jButtonÑ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonÑMousePressed(evt);
            }
        });

        jButtonO.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonO.setText("O");
        jButtonO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonOMousePressed(evt);
            }
        });

        jButtonP.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonP.setText("P");
        jButtonP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonPMousePressed(evt);
            }
        });

        jButtonQ.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonQ.setText("Q");
        jButtonQ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonQMousePressed(evt);
            }
        });

        jButtonX.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonX.setText("X");
        jButtonX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonXMousePressed(evt);
            }
        });

        jButtonY.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonY.setText("Y");
        jButtonY.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonYMousePressed(evt);
            }
        });

        jButtonZ.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonZ.setText("Z");
        jButtonZ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonZMousePressed(evt);
            }
        });

        jButtonU.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonU.setText("U");
        jButtonU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonUMousePressed(evt);
            }
        });

        jButtonV.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonV.setText("V");
        jButtonV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonVMousePressed(evt);
            }
        });

        jButtonW.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonW.setText("W");
        jButtonW.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonWMousePressed(evt);
            }
        });

        jButton28.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton28MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonA, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonB, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonD, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonE, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonF, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonG, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonÑ, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonO, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonP, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonQ, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonR, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonS, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonT, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonH, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonI, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonJ, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonK, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonL, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonM, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonN, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonU, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonV, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonW, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonX, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonY, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonZ, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(299, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonA, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonB, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonD, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonE, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonF, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonG, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonH, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonI, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonJ, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonK, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonL, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonM, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonN, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonÑ, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonO, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonP, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonQ, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonR, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonS, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonT, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonU, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonV, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonW, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonX, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonY, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonZ, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAMousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonAMousePressed

    private void jButtonBMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBMousePressed

        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonBMousePressed

    private void jButtonCMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCMousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonCMousePressed

    private void jButtonDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDMousePressed
       chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonDMousePressed

    private void jButtonEMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEMousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonEMousePressed

    private void jButtonFMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFMousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonFMousePressed

    private void jButtonGMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGMousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonGMousePressed

    private void jButtonLMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLMousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonLMousePressed

    private void jButtonMMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMMousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonMMousePressed

    private void jButtonNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNMousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonNMousePressed

    private void jButtonHMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHMousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonHMousePressed

    private void jButtonIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonIMousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonIMousePressed

    private void jButtonJMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonJMousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonJMousePressed

    private void jButtonKMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonKMousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonKMousePressed

    private void jButtonRMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRMousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonRMousePressed

    private void jButtonSMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSMousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonSMousePressed

    private void jButtonTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTMousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonTMousePressed

    private void jButtonÑMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonÑMousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonÑMousePressed

    private void jButtonOMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOMousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonOMousePressed

    private void jButtonPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPMousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonPMousePressed

    private void jButtonQMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonQMousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonQMousePressed

    private void jButtonXMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonXMousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonXMousePressed

    private void jButtonYMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonYMousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonYMousePressed

    private void jButtonZMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonZMousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonZMousePressed

    private void jButtonUMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUMousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonUMousePressed

    private void jButtonVMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVMousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonVMousePressed

    private void jButtonWMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonWMousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonWMousePressed

    private void jButton28MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton28MousePressed
        chequeaBoton((JButton) evt.getSource());
    }//GEN-LAST:event_jButton28MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAhorcado2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButtonA;
    private javax.swing.JButton jButtonB;
    private javax.swing.JButton jButtonC;
    private javax.swing.JButton jButtonD;
    private javax.swing.JButton jButtonE;
    private javax.swing.JButton jButtonF;
    private javax.swing.JButton jButtonG;
    private javax.swing.JButton jButtonH;
    private javax.swing.JButton jButtonI;
    private javax.swing.JButton jButtonJ;
    private javax.swing.JButton jButtonK;
    private javax.swing.JButton jButtonL;
    private javax.swing.JButton jButtonM;
    private javax.swing.JButton jButtonN;
    private javax.swing.JButton jButtonO;
    private javax.swing.JButton jButtonP;
    private javax.swing.JButton jButtonQ;
    private javax.swing.JButton jButtonR;
    private javax.swing.JButton jButtonS;
    private javax.swing.JButton jButtonT;
    private javax.swing.JButton jButtonU;
    private javax.swing.JButton jButtonV;
    private javax.swing.JButton jButtonW;
    private javax.swing.JButton jButtonX;
    private javax.swing.JButton jButtonY;
    private javax.swing.JButton jButtonZ;
    private javax.swing.JButton jButtonÑ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
